version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: fhir-postgres
    environment:
      - POSTGRES_DB=fhir
      - POSTGRES_USER=fhiruser
      - POSTGRES_PASSWORD=fhirpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fhiruser -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hapi-fhir-server:
    image: hapiproject/hapi:latest
    container_name: fhir-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/fhir
      - SPRING_DATASOURCE_USERNAME=fhiruser
      - SPRING_DATASOURCE_PASSWORD=fhirpassword
      - HAPI_FHIR_VERSION=R4
      - HAPI_FHIR_ALLOW_MULTIPLE_DELETE=true
      - HAPI_FHIR_ALLOW_EXTERNAL_REFERENCES=true
      - HAPI_FHIR_LOGGING_LEVEL=INFO
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
    driver: local
