apiVersion: apps/v1
kind: Deployment
metadata:
  name: hapi-fhir
  labels:
    app: hapi-fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi-fhir
  template:
    metadata:
      labels:
        app: hapi-fhir
    spec:
      containers:
      - name: hapi-fhir
        image: hapiproject/hapi:v6.2.5
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: hapi-fhir-config
              key: spring.datasource.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: hapi-fhir-secrets
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hapi-fhir-secrets
              key: db-password
        - name: SPRING_CONFIG_LOCATION
          value: "file:///app/config/application.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: hapi-fhir-config 